### ISSUE TITLE
Can't input decimals in some fields

### ISSUE THREAD

**Issue by excieve** [hotsyk/vulyk-declaration#5]
Fields that are intended for property area input (possibly some others) only allow integers.
Entering something like "48.6" or "48,6" triggers a validation message. Should accept both and post-process to a unified format.

**Comment by dimanech** [comment]
Fixed. See commit https://github.com/dimanech/form/commit/7ad082d57f34aafbbbd93ed9aba9b30f4a4d626b for details.

**Comment by mrgambal** [comment]
:+1:

**Comment by mrgambal** [comment]
:+1:
